name: GitHub Bot

on:
  # Watch for changes on PR state, assignees, labels, head branch and draft/ready status
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize # PR head updated
      - converted_to_draft
      - ready_for_review

  # Watch for changes on PR comment
  issue_comment:
    types: [created, edited, deleted]

  # Manual run from GitHub Actions interface
  workflow_dispatch:
    inputs:
      pull-request-list:
        description: "PR(s) to process: specify 'all' or a comma separated list of PR numbers, e.g. '42,1337,7890'"
        required: true
        default: all
        type: string

jobs:
  # This job creates a matrix of PR numbers based on the inputs from the various
  # events that can trigger this workflow so that the process-pr job below can
  # handle the parallel processing of the pull-requests
  define-prs-matrix:
    name: Define PRs matrix
    # Prevent bot from retriggering itself
    if: ${{ github.actor != vars.GH_BOT_LOGIN }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      pr-numbers: ${{ steps.pr-numbers.outputs.pr-numbers }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: contribs/github-bot/go.mod

      - name: Generate matrix from event
        id: pr-numbers
        working-directory: contribs/github-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run . matrix -matrix-key 'pr-numbers' -verbose

  # This job processes each pull request in the matrix individually while ensuring
  # that a same PR cannot be processed concurrently by mutliple runners
  process-pr:
    name: Process PR
    needs: define-prs-matrix
    # Just skip this job if PR numbers matrix is empty (prevent failed state)
    if: needs.define-prs-matrix.outputs.pr-numbers != '[]' && needs.define-prs-matrix.outputs.pr-numbers != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run one job for each PR to process
        pr-number: ${{ fromJSON(needs.define-prs-matrix.outputs.pr-numbers) }}
    concurrency:
      # Prevent running concurrent jobs for a given PR number
      group: ${{ matrix.pr-number }}
    outputs:
      check-run: ${{ steps.github-bot.outputs.check-run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: contribs/github-bot/go.mod

      - name: Run GitHub Bot
        id: github-bot
        working-directory: contribs/github-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
        run: go run . check -pr-numbers '${{ matrix.pr-number }}' -verbose

  # This job displays a GitHub Check Run using the output of the process-pr job
  check-run:
    name: Generate Check Run
    needs: process-pr
    if: always() # Run even if process-pr job failed
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required by Check Run API

    steps:
      - name: Process PR succeeded
        if: ${{ needs.process-pr.result == 'success' }}
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ fromJSON(needs.process-pr.outputs.check-run).name }}
          conclusion: ${{ fromJSON(needs.process-pr.outputs.check-run).conclusion }}
          details_url: ${{ fromJSON(needs.process-pr.outputs.check-run).details_url }}
          output: |
            {
              "title":"${{ fromJSON(needs.process-pr.outputs.check-run).title }}",
              "summary":"${{ fromJSON(needs.process-pr.outputs.check-run).summary }}",
              "text_description":"${{ fromJSON(needs.process-pr.outputs.check-run).description }}"
            }

      - name: Process PR failed
        if: ${{ needs.process-pr.result == 'failure' || needs.process-pr.result == 'cancelled' }}
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Name
          conclusion: failure
          output: |
            {
              "title":"title",
              "summary":"summary",
            }
